apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app: nginx
  name: nginx-deployment

spec:
  replics: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metdata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx  
